#连接数据库
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bills?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: admin
      initialSize: 3
      minIdle: 3
      maxActive: 30
      maxWait: 15000
      validationQuery: SELECT 'x'
#mybaitsplus的配置
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  configuration:
    global-config:
      db-config:
        id-type: auto  #配置全局的ID自动增长
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl